# 마이그레이션 드리프트 가드 — 모델을 고치고 마이그레이션을 빠뜨린 채 머지되지 않게 (backend.md §8)
from alembic import command
from alembic.config import Config

from tests.conftest import API_ROOT


def test_migrations_match_models(migrated_db: str) -> None:
    """모델과 마이그레이션이 어긋나면 AutogenerateDiffsDetected로 실패한다.

    `uv run alembic check`와 같은 검사인데 테스트로 두는 이유 — 실 DB가 있어야 도는 검사이고,
    그 DB를 이미 testcontainers가 띄워두므로 CI에 별도 서비스 컨테이너를 배선할 필요가 없다.
    sync 테스트인 이유 — env.py가 `asyncio.run()`으로 도는데 실행 중인 루프 안에서는 못 부른다.
    """
    config = Config(str(API_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(API_ROOT / "alembic"))

    command.check(config)
