# Alembic 마이그레이션 — accounts + sessions (#100 인증)
"""accounts + sessions

계정은 (id, iss, sub, created_at)이 전부다 — 이메일·프로필 컬럼은 없다(backend.md §12.1).
세션의 FK는 ON DELETE CASCADE다 — 탈퇴 시 계정 삭제 하나로 세션까지 파기된다(§12.3).

Revision ID: a8dc76751b1a
Revises: 6b8076167b5b
Create Date: 2026-07-17

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel의 str 필드는 sqlmodel.sql.sqltypes.AutoString으로 렌더된다 — 없으면 NameError
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8dc76751b1a"
down_revision: str | Sequence[str] | None = "6b8076167b5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("iss", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iss", "sub", name="uq_accounts_iss_sub"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_account_id"), "sessions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_account_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("accounts")
    # ### end Alembic commands ###
